import pandas as pd
import matplotlib.pyplot as plt

# =====================================================================
# 1. INSERT CPU SEQUENTIAL TIMES HERE (Baseline T_seq)
# You must run the matmul_cpu.c file and note the times here in SECONDS
# (Remember the professor's rule: CPU times must be > 30s)
# =====================================================================
BEST_SEQ_TIMES = {
    5000: 91.53734,   # EXAMPLE: Replace with the TRUE CPU time for N=2000
    10000: 764.730147,  # EXAMPLE: Replace with the TRUE CPU time for N=4000
    15000: 2750.0  # EXAMPLE: Replace with the TRUE CPU time for N=8000
}
 
# 2. Load data from the CSV generated by the CUDA Bash script
csv_path = '../results/cuda_scalability.csv'
try:
    df = pd.read_csv(csv_path)
except FileNotFoundError:
    print(f"Error: File {csv_path} not found.")
    exit(1)

# 3. Prepare the plotting area (1 row, 2 columns for Speedup and Efficiency)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

sizes = df['N'].unique()
colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
markers = ['o', 's', '^']

# 4. Calculate and plot the curves for each dimension N
for i, n in enumerate(sizes):
    # Check if we have inserted the sequential time for this N
    if n not in BEST_SEQ_TIMES:
        print(f"Warning: Missing CPU time for N={n}. Skipping this plot.")
        continue
        
    subset = df[df['N'] == n].sort_values('BlockSize_1D')
    block_sizes = subset['BlockSize_1D'].values
    threads_per_block = subset['ThreadsPerBlock'].values # Retrieved from CSV
    kernel_ms = subset['Kernel_ms'].values
    
    # Convert Kernel time from milliseconds to seconds
    kernel_sec = kernel_ms / 1000.0
    
    # The base sequential time (T_seq) for this specific N
    t_seq = BEST_SEQ_TIMES[n]
    
    # Speedup calculation: T_seq_CPU / T_kernel_GPU
    speedup = t_seq / kernel_sec
    
    # Efficiency calculation: Speedup / Number of Threads per Block
    efficiency = speedup / threads_per_block
    
    # Custom labels for the X-axis (shows BlockSize and number of threads)
    x_labels = [f"{b}x{b}\n({b*b} th)" for b in block_sizes]
    
    # Plot the Speedup curve on the first graph (ax1)
    ax1.plot(x_labels, speedup, marker=markers[i], color=colors[i], 
             linewidth=2.5, markersize=10, label=f'N = {n} (T_seq = {t_seq}s)')
             
    # Plot the Efficiency curve on the second graph (ax2)
    ax2.plot(x_labels, efficiency, marker=markers[i], color=colors[i], 
             linewidth=2.5, markersize=10, label=f'N = {n}')

# 5. Graph 1 Formatting: Speedup
ax1.set_title('CUDA MatMul: Speedup vs Block Size', fontsize=14, fontweight='bold')
ax1.set_xlabel('2D Block Configuration (BlockSize_1D)', fontsize=12)
ax1.set_ylabel('Speedup (T_seq_CPU / T_kernel_GPU)', fontsize=12)
ax1.grid(True, linestyle='--', alpha=0.7)
ax1.legend(fontsize=11, loc='upper left')

# 6. Graph 2 Formatting: Efficiency
ax2.set_title('CUDA MatMul: Efficiency vs Block Size', fontsize=14, fontweight='bold')
ax2.set_xlabel('2D Block Configuration (BlockSize_1D)', fontsize=12)
ax2.set_ylabel('Efficiency (Speedup / Threads per Block)', fontsize=12)
ax2.grid(True, linestyle='--', alpha=0.7)
ax2.legend(fontsize=11, loc='upper right')

# 7. Optimize layout and save
plt.tight_layout()
output_file = '../results/cuda_speedup_efficiency_graphs.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"Graphs successfully generated in: {output_file}")

# Display the graphs
plt.show()