import pandas as pd
import matplotlib.pyplot as plt

# 1. Load data from the CSV generated by the Bash script
csv_path = '../results/scalability_data.csv'

try:
    df = pd.read_csv(csv_path)
except FileNotFoundError:
    print(f"Error: File {csv_path} not found.")
    exit(1)

# 2. Prepare the plotting area (1 row, 2 columns for side-by-side graphs)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

sizes = df['N'].unique()
colors = ['#1f77b4', '#ff7f0e', '#2ca02c'] # Professional colors (Blue, Orange, Green)
markers = ['o', 's', '^']

# 3. Calculate and plot curves for each dimension N
for i, n in enumerate(sizes):
    # Filter data for size N and sort by number of threads
    subset = df[df['N'] == n].sort_values('Threads')
    threads = subset['Threads'].values
    times = subset['Time_s'].values
    
    # Find the base sequential time (T1) for this specific N
    t1 = subset[subset['Threads'] == 1]['Time_s'].values[0]
    
    # Vectorized calculation of Speedup and Efficiency
    speedup = t1 / times
    efficiency = speedup / threads
    
    # Plot the Speedup curve
    ax1.plot(threads, speedup, marker=markers[i], color=colors[i], 
             linewidth=2, markersize=8, label=f'N = {n}')
    
    # Plot the Efficiency curve
    ax2.plot(threads, efficiency, marker=markers[i], color=colors[i], 
             linewidth=2, markersize=8, label=f'N = {n}')

# 4. Add ideal lines (the theoretical maximum reachable)
max_threads = df['Threads'].max()
ax1.plot([1, max_threads], [1, max_threads], 'k--', alpha=0.5, label='Ideal Speedup')
ax2.plot([1, max_threads], [1, 1], 'k--', alpha=0.5, label='Ideal Efficiency')

# 5. Graph 1 Formatting: Speedup
ax1.set_title('OpenMP Scalability: Speedup', fontsize=14, fontweight='bold')
ax1.set_xlabel('Number of Threads (p)', fontsize=12)
ax1.set_ylabel('Speedup (Sp = T1 / Tp)', fontsize=12)
ax1.set_xticks(df['Threads'].unique())
ax1.grid(True, linestyle='--', alpha=0.7)
ax1.legend(fontsize=11)

# 6. Graph 2 Formatting: Efficiency
ax2.set_title('OpenMP Scalability: Efficiency', fontsize=14, fontweight='bold')
ax2.set_xlabel('Number of Threads (p)', fontsize=12)
ax2.set_ylabel('Efficiency (Ep = Sp / p)', fontsize=12)
ax2.set_xticks(df['Threads'].unique())
ax2.set_ylim([0, 1.1]) # Efficiency rarely exceeds 1.0 (or 1.1 with super-linear cache effects)
ax2.grid(True, linestyle='--', alpha=0.7)
ax2.legend(fontsize=11)

# 7. Optimize layout and save
plt.tight_layout()
output_file = '../results/scalability_graphs.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"Graphs successfully generated in: {output_file}")

# Display the graphs
plt.show()